### ISSUE TITLE
Add section on IDE integration

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/catch-lest-other-comparison#2]

**Comment by willwray** [comment]
Looks like this issue is done as there is already a section on IDE integration...

Suggest to add VS Code, also as blanks for now as it's popular vscode-cpptools extension doesn't appear to support test output yet (c.f https://github.com/Microsoft/vscode-cpptools/issues/1079)

While you're at it -

For the distribution section you could add linux package manager.
On Fedora catch is included in `catch-devel` package:
```
>dnf list catch-devel
catch-devel.x86_64       1.10.0-1.fc27
```
Also, refs [6] & [7] at the bottom credited to Phils Nash. Who he?

A great resource, thanks.

**Comment by martinmoene** [comment]
Thanks!

>Also, refs [6] & [7] at the bottom credited to Phils Nash. Who he?

Argh...

**Comment by martinmoene** [comment]
- [ ] Fix Phil's name in refs 6, 7
- [ ] Add Visual Studio Code to IDE integration
- [ ] Add Linux package manager(s)

**Comment by onqtam** [comment]
there is also a [debian package](https://packages.debian.org/sid/main/doctest-dev) for doctest :)

**Comment by martinmoene** [comment]
and [more...](https://repology.org/metapackage/doctest/information)
