### ISSUE TITLE
Errors found

### ISSUE THREAD

**Issue by horenmar** [martinmoene/catch-lest-other-comparison#4]
Sorry for the bad issue name, but I didn't want to open up a new one per each thing I noticed from cursory reading

* Catch 2 throws out data generators completely for now (they might or might not make it back in before proper release).
* Catch allows tests in header files and accompanying the implementation code (not in libraries though), it just isn't recommended because of its compilation times.
* "CI code anaylisis" -> "CI code analysis"

Also Catch recently started providing a link to wandbox with the single header preloaded.

**Comment by martinmoene** [comment]
Thanks @horenmar, will process these next week.

**Comment by martinmoene** [comment]
Fixed in 7b1846be5221ce3fe123a3988ca44a1041265520

- [x] Catch 2 throws out data generators completely for now (they might or might not make it back in before proper release).
- [x] Catch allows tests in header files and accompanying the implementation code (not in libraries though), it just isn't recommended because of its compilation times.
- [x] "CI code anaylisis" -> "CI code analysis"
