### ISSUE TITLE
[doctest] some fixes

### ISSUE THREAD

**Issue by onqtam** [martinmoene/catch-lest-other-comparison#5]
Here are some fixes for the comparison table:

- ```Count selected tests``` - doctest supports it with the [count](https://github.com/onqtam/doctest/blob/master/doc/markdown/commandline.md) option
- ```Time duration of tests``` - doctest supports it with the [duration](https://github.com/onqtam/doctest/blob/dev/doc/markdown/commandline.md) option - currently documented only in dev but is implemented in master - will be mentioned in master soon
- ```macOS / gcc``` - its tested on travis using homebrew - separately from xcode
- ```Windows / gcc``` - tested with MinGW-w64 latest - currently gcc 7
- ```Size, LOC``` - currently 5600+ lines - soon will hit the 6k mark so might as well say "6000" (also Catch seems to be 11600+)
- ```PVC-Studio``` - should be renamed to ```PVS-Studio```

**Comment by martinmoene** [comment]
Thanks @onqtam, will process these next week.

**Comment by martinmoene** [comment]
Fixed in b6ee51b2fea50e7e8e1234606f4694a4b79b0c03

- [x] Count selected tests - doctest supports it with the count option
- [x] Time duration of tests - doctest supports it with the duration option - currently documented only in dev but is implemented in master - will be mentioned in master soon
- [x] macOS / gcc - its tested on travis using homebrew - separately from xcode
- [x] Windows / gcc - tested with MinGW-w64 latest - currently gcc 7
- [x] PVC-Studio - should be renamed to PVS-Studio

>Size, LOC - currently 5600+ lines - soon will hit the 6k mark so might as well say "6000" (also Catch seems to be 11600+)

Table presents actual code lines  (non-empty, non-comment) as reported by CodeBlocks File > properties.
